import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import React, { createContext, Dispatch, ReactNode, useContext, useEffect, useState } from 'react';
import { selectedLang } from '../components/constants';

i18n
  .use(initReactI18next)
  .init({
    resources: {

      // ════════════════════════════════════════════════════════════════════
      // ENGLISH
      // ════════════════════════════════════════════════════════════════════
      en: {
        translation: {
          nav: {
            home: 'Home',
            menu: 'Menu',
            cart: 'Your cart',
            orders: 'Orders',
            settings: 'Settings',
            statistics: 'Statistics',
            signOut: 'Sign out',
          },

          product: {
            type: 'Product type',
            settings: 'Product settings',
            label: 'Product',
            soldOut: 'Sold out',
            sizes: 'Sizes',
            price: 'Price',
            currency: 'MAD',
            preview: 'Product preview',
            info: 'Product info',
            details: 'Product details',
            reviews: 'Product reviews',
            loading: 'Products are loading...',
            noneYet: 'New products will come!',
            stayTuned: 'Stay tuned!',
            view: 'View the product',
            addToCart: 'Add to cart',
            size: 'Size',
            category: 'Category',
            ref: 'Ref',
            name: 'Name',
            before: 'Before',
            promotion: 'Discount',
            off: 'Off',
            readMore: 'Read more',
            readLess: 'Read less',
            quantity: 'Quantity',
            availability: 'Availability',
          },

          productTypes: {
            shoe: 'Shoes',
            sandal: 'Sandals',
            shirt: 'Shirts',
            pant: 'Pants',
          },

          cart: {
            title: 'Your cart',
            empty: 'There are no items in your shopping cart',
            clear: 'Clear cart',
            toCart: 'To cart',
            addSuccess: 'A new item is added!',
            sizeNotSelected: 'Size is not selected!',
            quantityAction: 'Quantity/Action',
            total: 'Total',
            cleared: 'The cart is cleared',
            itemRemoved: 'The item is removed',
            shopNow: 'Shop now',
          },

          order: {
            summary: 'ORDER SUMMARY',
            shipping: 'Shipping',
            other: 'Other',
            totalAmount: 'Total amount',
            yourOrder: 'Your order',
            orderId: 'Order ID',
            checkoutNow: 'Checkout now!',
            details: 'Order details',
          },

          confirm: {
            removeItem: 'Are you sure you want to remove this item?',
            removeAll: 'Are you sure you want to remove all the items?',
            deleteTitle: 'Delete confirmation',
            clearAllItems: 'Clear all items',
            remove: 'Remove',
            cancelBack: 'Cancel and Back',
            delete: 'Delete',
          },

          delivery: {
            label: 'Delivery',
            free: 'Free',
            time: 'Delivery time',
            expected: 'expected',
            from: 'from',
            to: 'to',
            cityOnly: 'Currently, delivery is only available in the city of Laayoune.',
          },

          payment: {
            portal: 'Payment portal',
            creditCard: 'Credit card',
            cod: 'Cash on delivery COD',
            choose: 'Please choose a payment method!',
            chosen: 'Chosen payment method',
            notChosen: 'Not chosen yet!',
            methods: 'Payments',
            pay: 'Pay',
            checkoutAlert: 'Fill the form firstly, then choose the payment method 👍🏻',
            overlayUrlTitle:      'Initializing Payment',
            overlayUrlSub:        'Setting up your secure session…',
            overlayCodTitle:      'Placing Your Order',
            overlayCodSub:        'Confirming your order…',
            overlayRedirectTitle: 'Redirecting to Payment',
            overlayRedirectSub:   'Taking you to the payment page…',
          },

          transaction: {
            info: 'Transaction infos',
            code: 'Code',
            currency: 'Currency',
            amount: 'Amount',
            transactionId: 'Transaction ID',
            success: 'Your transaction is successfully completed',
            downloadTicket: 'Download e-command ticket',
            thank: 'Thank you for your confidence',
            verifying:            'Verifying Payment',
            verifyingSub:         'Confirming with payment gateway…',
            processing:           'Processing Order',
            processingSub:        'Recording your order…',
            emailing:             'Sending Invoice',
            emailingSub:          'Emailing your receipt…',
            done:                 'All Done!',
            doneSub:              'Redirecting you now…',
            pleaseWait:           'Please wait…',
            attemptOf:            'Attempt {{current}} of {{max}}',
            waitingBeforeRetry:   'Waiting before retry {{current}} of {{max}}…',
            retryTitle:           'Payment could not be confirmed',
            retryDefaultReason:   'Your payment could not be verified. Please try again.',
            retryLabel:           'Transaction',
            retryOrder:           'Order',
            retryBtn:             'Try Again',
            cancelBtn:            'Cancel order',
            retryNote:            'Your reserved items are still held. Retrying will take you back to the payment page without creating a new order.',
            retryBusy:            'Please wait…',
            errorTitle:           'Something went wrong',
            errorNote:            'Please contact our support team with the details above.',
            failedTitle:          'Payment Failed',
            failedDefaultMsg:     'Something went wrong with your payment.',
            failedOrderId:        'Order ID',
            failedTransactionId:  'Transaction ID',
            failedErrorCode:      'Error Code',
            failedSupportNote:    'Please keep your transaction ID and contact support if you were charged.',
            failedGoHome:         'Go Home',
            failedTryAgain:       'Try Again',
            failedCategory_cancelled:          'Payment Cancelled',
            failedCategory_insufficient_funds: 'Insufficient Funds',
            failedCategory_card_declined:      'Card Declined',
            failedCategory_card_expired:       'Card Expired',
            failedCategory_auth_failed:        '3-D Secure Failed',
            failedCategory_timeout:            'Session Timed Out',
            failedCategory_generic:            'Payment Failed',
            failedHintCancelled:  'You cancelled the payment. Your reserved items are still held — click "Try Again" to return to the payment page.',
            failedHintFunds:      'Your card was declined due to insufficient funds. Please use a different card or top up your account and try again.',
            failedHintDeclined:   'Your card was declined by the bank. Please check your card details or contact your bank before trying again.',
            failedHintExpired:    'Your card appears to be expired. Please update your card information and try with a valid card.',
            failedHintAuth:       '3-D Secure authentication failed. Please try again and follow the verification steps sent by your bank.',
            failedHintTimeout:    'The payment session timed out. This can happen if the page was left open too long. Please try again.',
          },

          form: {
            firstName: { label: 'First name', required: 'Your first name is required' },
            lastName:  { label: 'Last name',  required: 'Your last name is required'  },
            fullName: 'Full name',
            email:   { label: 'E-mail',   required: 'Your e-mail is required'    },
            address: { label: 'Address',  required: 'Your address is required'   },
            city:    { label: 'City',     required: 'Your city is required'      },
            country: { label: 'Country', required: 'Your Country is required' },
            phone: {
              label:         'Phone number',
              required:      'Your phone number is required',
              minLength:     'Minimum 10 characters',
              invalidLength: 'Phone number length is invalid',
              invalidFormat: 'Enter a valid phone number: 06.., 07.. or +212..',
            },
            save: 'Save',
            saveChanges: 'Save modifications',
            modify: 'Modify',
            submit: 'Submit',
            clientInfo: 'Client informations',
            selectCity: 'Select your city',
          },

          review: {
            title: 'Product reviews',
            add: 'Add your review',
            submit: 'Add the review',
            stars: 'Stars',
            username: 'Username',
            yourReview: 'Your review',
            firstReview: 'Put the first review!',
            fillAllFields: 'Please fill in all fields before submitting.',
            city1: 'Verified buyer',
            city2: 'Verified buyer',
            city3: 'Verified buyer',
          },

          pagination: { next: 'Next', previous: 'Previous' },

          ui: {
            loading: 'Loading . . .',
            back: 'Back',
            search: 'Search',
            reset: 'Reset',
            enterName: 'Enter a name',
            enterRef: 'Enter a ref',
            save: 'Save',
          },

          home: {
            promotions: 'Our offers and promotions',
            products: 'Our products',
            goToShoes: 'Go to shoes section',
            goToSandals: 'Go to sandals section',
            goToShirts: 'Go to shirts section',
            goToPants: 'Go to pants section',
            moreShoes: 'More shoes',
            moreSandals: 'More sandals',
            moreShirts: 'More shirts',
            morePants: 'More pants',

            hero: {
              cta: 'Shop now',
              howItWorks: 'How it works',
              slide1: {
                tag: 'New collection',
                headline: 'Find your fit, in just a few taps',
                sub: 'Shoes, sandals, shirts and pants — handpicked styles, delivered to your door.',
              },
              slide2: {
                tag: 'Trending now',
                headline: 'Step into comfort this season',
                sub: 'Everyday sandals built for warm days and easy living.',
              },
              slide3: {
                tag: 'Just dropped',
                headline: 'Fresh shirts, made for every day',
                sub: 'Casual and sharp cuts that move with you.',
              },
            },

            shopByCategory: 'Shop by category',
            shopByCategorySub: 'Everything you need, organized simply — pick a category to start browsing.',

            featured: 'New arrivals',
            featuredSub: 'Fresh stock, added regularly — see what just landed.',
            viewAll: 'View all products',

            cat: {
              fallbackDesc: 'Explore the full range',
              shoeDesc: 'Everyday and sport styles',
              sandalDesc: 'Lightweight warm-weather comfort',
              shirtDesc: 'Casual and sharp cuts',
              pantDesc: 'Modern fits for every day',
            },
          },

          trust: {
            delivery: 'Fast delivery',
            deliverySub: 'Tracked shipping to your door',
            quality: 'Checked quality',
            qualitySub: 'Every item inspected before shipping',
            secure: 'Secure checkout',
            secureSub: 'Your information stays protected',
            support: 'Real support',
            supportSub: 'We reply within a few hours',
          },

          hiw: {
            title: 'Shopping made simple',
            sub: 'From browsing to your doorstep — four easy steps.',
            step1: { title: 'Browse the collection', desc: 'Explore shoes, sandals, shirts and pants. Filter by size, style or price.' },
            step2: { title: 'Pick your size', desc: 'Only in-stock sizes are shown, so there are no surprises at checkout.' },
            step3: { title: 'Place your order', desc: 'Add to your cart and confirm your details — no account required.' },
            step4: { title: 'Get it delivered', desc: 'We bring it to your door. Track your order every step of the way.' },
          },

          promo: {
            title: 'This week, a discount of up to',
            sub: 'Selected styles are on sale right now. New deals added every week.',
            cta: 'See the deals',
          },

          testimonials: {
            title: 'What shoppers are saying',
            sub: 'Real reviews from real customers.',
            r1: 'Great quality and the fit was exactly right. Delivery was quicker than I expected.',
            r2: 'Comfortable, well made, and easy to order. I will be back for more.',
            r3: 'Easy checkout and the package arrived in great condition. Highly recommend.',
          },

          newsletter: {
            eyebrow: 'Stay in the loop',
            title: 'New drops and exclusive deals, first',
            sub: 'Join the list and be the first to know when fresh styles arrive.',
            cta: 'Notify me',
            invalid: 'Please enter a valid email address.',
            success: "You're in — watch your inbox.",
            thanks: "Thanks! We'll be in touch.",
          },

          admin: {
            orders: {
              remaining:       'Remaining orders',
              waitingDelivery: 'Waiting for delivery',
              delivered:       'Delivered orders',
              all:             'All orders',
              notConfirmed:    'Orders not confirmed',
              showAll:         'Show all orders',
              noRemaining:     'No remaining order found',
              noWaitingDelivery: 'No order waiting for delivery',
              noDelivered:     'No order delivered yet',
              noOrders:        'No order yet',
              noProducts:      'No products found for this order',
              treated:         'The order is treated successfully',
              alreadyTreated:  'The order is already treated',
              process:         'Process',
              waiting:         'Waiting',
              done:            'Done',
              treated_label:   'Treated',
              status:          'Status',
              date:            'Date',
              action:          'Action',
              extractDeliveryForm: 'Extract delivery form',
              extractSuccess:  'Delivery form was extracted successfully',
            },
            deficiency: {
              title:             "Quantity's deficiency",
              current:           'Current deficiencies',
              showAll:           'Show all deficiencies',
              process:           'Process',
              message:           'Please process the deficiencies, then process the order!',
              confirm:           'Confirmation of deficiency treatment',
              success:           'The deficiency was treated successfully',
              error:             'Failed to process the deficiency. Please try again.',
              noFound:           'No deficiency found',
              quantityRequested: 'Quantity requested',
            },
            product: {
              select:           'Select a product',
              mainImage:        'Main image',
              additionalImages: 'Additional Images',
              newer:            'Newer product',
              uploadedImages:   'Uploaded images',
              delete:           'Delete a product',
              modify:           'Modify a product',
              addData:          'Add product data',
              add:              'Add a product',
              advancedSearch:   'Advanced search',
              management:       'Management of products',
              managementOf:     'Products management of',
              noChosen:         'No product chosen',
              noData:           'This product does not contain any data',
              orderedProducts:  'Ordered products',
              noCategoryData:   'No category data',
              categoryError:    'Add a category to the product in the settings first, then add one',
              addTypes:         'Add product types',
              addCategories:    'Add product categories',
              selectType:       'Select product type',
              selectCategory:   'Select a category',
            },
            overview: { general: 'General overview', notDeveloped: 'Not developed yet' },
            users: {
              manager:             'Users Manager',
              add:                 'Add a user',
              username:            'Username',
              password:            'Password',
              confirmPassword:     'Confirm password',
              passwordMismatch:    'Passwords do not match',
              role:                'Role',
              selectRole:          'Select user role',
              manager_role:        'Manager',
              admin_role:          'Admin',
              deliveryMan:         'Delivery man',
              registrationSuccess: 'Registration is succeeded',
            },
          },

          account: {
            profileTitle:    'My profile',
            tabOrders:       'My orders',
            tabProfile:      'My profile',
            noOrders:        'You have no orders yet.',
            ordersError:     'Failed to load your orders. Please try again.',
            saveSuccess:     'Profile updated successfully.',
            saveError:       'Failed to save changes. Please try again.',
            statOrders:      'Orders',
            statConfirmed:   'Confirmed',
            statDelivered:   'Delivered',
            statSpent:       'Total spent',
            statusConfirmed: 'Confirmed',
            statusCod:       'Cash on delivery',
            statusPending:   'Pending',
            statusFailed:    'Failed',
            delivered:       'Delivered',
            onlinePayment:   'Online payment',
            codPayment:      'Cash on delivery',
            articles:        'items',
            article:         'item',
            loyaltyPerks:    'Loyalty Benefits',
            loyaltyLabel:    'Loyalty Level',
            loyaltyToNext:   'Points remaining to reach the next level',
            loyaltyPoints:   'Loyalty Points',
            confirmSaveTitle: 'Save Changes',
            confirmSaveSub:   'Are you sure you want to save your changes?',
            noChanges:        'No changes were made',
            changeAvatar:     'Change Avatar',
            // ── Order status pipeline (customer account view) ────────────
            stepPlaced:        'Order placed',
            stepPayment:       'Payment',
            stepProcessing:    'Processing',
            stepDelivery:      'Delivery',
            processingOngoing: 'Being prepared',
            processingDone:    'Ready',
            paymentFailed:     'Payment failed',
            paymentFailedNote: 'Your payment could not be confirmed, so this order is on hold. Please contact us or place a new order.',
            readyToShip:       'Ready to ship',
            outForDelivery:    'Out for delivery',
          },

          tracking: {
            title:          'Order state tracker',
            enterOrderId:   'Enter your order ID or name',
            placeholder:    'Order ID or customer name',
            search:         'Search',
            searching:      'Searching the order',
            notValidated:   'Your order is on the way to be validated',
            validated:      'Your order is validated and it is on the way to you',
            attempts:       'Searching attempts',
            limitReached:   'You have reached the search attempt limit. You can try again tomorrow.',
            noValidId:      'is not a valid order ID',
            noOrderFound:   'There is no order associated with the order ID provided',
            idProvided:     'Order ID provided',
            hint:           'Enter the order number or customer name to see the order details.',
            orderDetails:   'Order details',
            orderId:        'Order ID',
            date:           'Date',
            paymentMode:    'Payment mode',
            paymentStatus:  'Payment status',
            delivery:       'Delivery',
            total:          'Total',
            products:       'Ordered products',
            product:        'Product',
            category:       'Category',
            size:           'Size',
            qty:            'Qty',
            price:          'Price',
            newSearch:      'New search',
            goBack:         'Go back',
            limitHint:      'Please wait and try again later.',
            pending:        'Pending',
            delivered:      'Delivered',
            failed:         'Payment failed',
            cod:            'Cash on delivery',
            processing:     'In progress',
            online:         'Online payment',
            inProgress:     'In progress',
          },

          auth: {
            welcomeBack:    'Welcome back!',
            usernameLabel: 'Username',
            signOut:        'Sign out',
            signIn:         'Sign in',
            myAccount:      'My account',
            signInTitle:          'Welcome back',
            signInBtn:            'Sign in',
            noAccount:            'No account yet?',
            createOne:            'Create one',
            signUpTitle:          'Create your account',
            signUpBtn:            'Create account',
            haveAccount:          'Already have an account?',
            signInLink:           'Sign in',
            successTitle:         'Check your inbox!',
            successSub:           'We sent an activation link to {{email}}. Click it to activate your account.',
            goToSignIn:           'Go to sign in',
            emailLabel:           'Email address',
            emailPlaceholder:     'you@example.com',
            passwordLabel:        'Password',
            confirmPasswordLabel: 'Confirm password',
            firstNameLabel:       'First name',
            firstNamePlaceholder: 'Youssef',
            lastNameLabel:        'Last name',
            lastNamePlaceholder:  'Alaoui',
            phoneLabel:           'Phone (optional)',
            phonePlaceholder:     '+212 6XX XXX XXX',
            addressLabel:         'Address (optional)',
            addressPlaceholder:   '12 Rue Mohammed V, Casablanca',
            passwordHint:         'Minimum 8 characters.',
            passwordMismatch:     'Passwords do not match.',
            passwordTooShort:     'Password must be at least 8 characters.',
            showPassword:         'Show password',
            hidePassword:         'Hide password',
            genericError:         'Something went wrong. Please try again.',
            brandTagline:         'Shop premium fashion delivered across Morocco.',
            checkoutHowToContinue: 'How would you like to continue?',
            checkoutSub:           'Sign in for faster checkout and order tracking.',
            checkoutWithAccount:   'Continue with my account',
            checkoutWithAccountSub:'Pre-fill your details and track your orders.',
            checkoutAsGuest:       'Continue as guest',
            checkoutAsGuestSub:    'No account needed. Fill in your details manually.',
            continueAsGuest:       'Switch to guest',
            guestNudge:            'Save time on your next order —',
            or:                    'or',
            activating:            'Activating your account…',
            activateSuccessTitle:  'Account activated!',
            activateSuccessSub:    'Your account is now active. Welcome to Al-Firdaous Store!',
            activateAlreadyTitle:  'Already activated',
            activateAlreadySub:    'Your account is already active. You can sign in.',
            activateErrorTitle:    'Invalid link',
            activateErrorSub:      'This activation link is invalid or has already been used.',
            activateRedirect:      'Redirecting to sign in in {{seconds}}s…',
            // ── Password strength meter ──────────────────────────────────
            strengthLength:   'At least 8 characters',
            strengthUppercase:'One uppercase letter',
            strengthNumber:   'One number',
            strengthSpecial:  'One special character',
            strengthWeak:     'Weak',
            strengthFair:     'Fair',
            strengthGood:     'Good',
            strengthStrong:   'Strong',
            passwordsMatch:   'Passwords match',
          },

          footer: {
            followUs:            'Follow us',
            contactUs:           'Contact us',
            policies:            'Policies',
            privacyPolicy:       'Privacy policy',
            usePolicy:           'General conditions of use',
            policiesNotAccepted: 'Please accept the terms and privacy policy.',
          },

          error: {
            elementNotFound: 'The element is not found!',
            pageNotFound:    'Oops! This page does not exist.',
          },
        },
      },

      // ════════════════════════════════════════════════════════════════════
      // FRENCH
      // ════════════════════════════════════════════════════════════════════
      fr: {
        translation: {
          nav: {
            home: 'Accueil',
            menu: 'Menu',
            cart: 'Votre panier',
            orders: 'Ordres',
            settings: 'Paramètres',
            statistics: 'Statistiques',
            signOut: 'Déconnexion',
          },

          product: {
            type: 'Type de produit',
            settings: 'Paramètres du produit',
            label: 'Produit',
            soldOut: 'Épuisé',
            sizes: 'Tailles',
            price: 'Prix',
            currency: 'MAD',
            preview: 'Aperçu du produit',
            info: 'Infos du produit',
            details: 'Détails du produit',
            reviews: 'Avis sur les produits',
            loading: 'Chargement des produits...',
            noneYet: 'De nouveaux produits arriveront !',
            stayTuned: "Restez à l'écoute !",
            view: 'Voir le produit',
            addToCart: 'Ajouter au panier',
            size: 'Taille',
            category: 'Catégorie',
            ref: 'Ref',
            name: 'Nom',
            before: 'Avant',
            promotion: 'Promotion',
            off: 'Moins',
            readMore: 'Lire plus',
            readLess: 'Lire moins',
            quantity: 'Quantité',
            availability: 'Disponibilité',
          },

          productTypes: {
            shoe: 'Chaussures',
            sandal: 'Sandales',
            shirt: 'Chemises',
            pant: 'Pantalons',
          },

          cart: {
            title: 'Votre panier',
            empty: "Il n'y a aucun article dans votre panier",
            clear: 'Vider le panier',
            toCart: 'Retour au panier',
            addSuccess: 'Un nouvel article est ajouté !',
            sizeNotSelected: "La taille n'est pas choisie !",
            quantityAction: 'Quantité/Action',
            total: 'Total',
            cleared: 'Le panier est vidé',
            itemRemoved: "L'élément est supprimé",
            shopNow: 'Achetez maintenant',
          },

          order: {
            summary: 'La commande',
            shipping: 'Transport',
            other: 'Autre',
            totalAmount: 'Montant',
            yourOrder: 'Votre commande',
            orderId: 'ID commande',
            checkoutNow: 'Checkout maintenant !',
            details: 'Détails de la commande',
          },

          confirm: {
            removeItem: 'Êtes-vous sûr de vouloir supprimer cet élément ?',
            removeAll: 'Êtes-vous sûr de vouloir supprimer tous les éléments ?',
            deleteTitle: 'Confirmation de suppression',
            clearAllItems: 'Effacer tous',
            remove: 'Supprimer',
            cancelBack: 'Annuler et revenir',
            delete: 'Supprimer',
          },

          delivery: {
            label: 'Livraison',
            free: 'Gratuit',
            time: 'Délai de livraison',
            expected: 'attendu',
            from: 'de',
            to: 'à',
            cityOnly: 'Actuellement, la livraison est disponible uniquement à la ville de Laâyoune.',
          },

          payment: {
            portal: 'Portail de paiement',
            creditCard: 'Carte bancaire',
            cod: 'Cash on delivery COD',
            choose: 'Merci de choisir une méthode de paiement !',
            chosen: 'Méthode de paiement choisie',
            notChosen: 'Pas encore choisi !',
            methods: 'Paiements',
            pay: 'Payer',
            checkoutAlert: "Remplissez d'abord le formulaire, puis choisissez le mode de paiement 👍🏻",
            overlayUrlTitle:      'Initialisation du paiement',
            overlayUrlSub:        'Configuration de votre session sécurisée…',
            overlayCodTitle:      'Passage de votre commande',
            overlayCodSub:        'Confirmation de votre commande…',
            overlayRedirectTitle: 'Redirection vers le paiement',
            overlayRedirectSub:   'Vous allez être redirigé vers la page de paiement…',
          },

          transaction: {
            info: 'Infos de transaction',
            code: 'Code',
            currency: 'Devise',
            amount: 'Montant',
            transactionId: 'ID transaction',
            success: 'Votre transaction est effectuée avec succès',
            downloadTicket: "Télécharger le ticket de l'e-commande",
            thank: 'Merci pour votre confiance !',
            verifying:            'Vérification du paiement',
            verifyingSub:         'Confirmation avec la passerelle de paiement…',
            processing:           'Traitement de la commande',
            processingSub:        'Enregistrement de votre commande…',
            emailing:             'Envoi de la facture',
            emailingSub:          "Votre reçu est en cours d'envoi…",
            done:                 'Tout est fait !',
            doneSub:              'Redirection en cours…',
            pleaseWait:           'Veuillez patienter…',
            attemptOf:            'Tentative {{current}} sur {{max}}',
            waitingBeforeRetry:   'Attente avant la tentative {{current}} sur {{max}}…',
            retryTitle:           "Le paiement n'a pas pu être confirmé",
            retryDefaultReason:   "Votre paiement n'a pas pu être vérifié. Veuillez réessayer.",
            retryLabel:           'Transaction',
            retryOrder:           'Commande',
            retryBtn:             'Réessayer',
            cancelBtn:            'Annuler la commande',
            retryNote:            'Vos articles sont toujours réservés. Réessayer vous ramènera à la page de paiement sans créer une nouvelle commande.',
            retryBusy:            'Veuillez patienter…',
            errorTitle:           "Une erreur s'est produite",
            errorNote:            "Veuillez contacter notre service d'assistance avec les détails ci-dessus.",
            failedTitle:          'Paiement échoué',
            failedDefaultMsg:     "Une erreur s'est produite lors de votre paiement.",
            failedOrderId:        'ID commande',
            failedTransactionId:  'ID transaction',
            failedErrorCode:      "Code d'erreur",
            failedSupportNote:    'Veuillez conserver votre ID de transaction et contacter le support si vous avez été débité.',
            failedGoHome:         'Accueil',
            failedTryAgain:       'Réessayer',
            failedCategory_cancelled:          'Paiement annulé',
            failedCategory_insufficient_funds: 'Fonds insuffisants',
            failedCategory_card_declined:      'Carte refusée',
            failedCategory_card_expired:       'Carte expirée',
            failedCategory_auth_failed:        'Échec 3-D Secure',
            failedCategory_timeout:            'Session expirée',
            failedCategory_generic:            'Paiement échoué',
            failedHintCancelled:  'Vous avez annulé le paiement. Vos articles sont toujours réservés — cliquez sur « Réessayer » pour revenir à la page de paiement.',
            failedHintFunds:      'Votre carte a été refusée en raison de fonds insuffisants. Veuillez utiliser une autre carte ou recharger votre compte et réessayer.',
            failedHintDeclined:   'Votre carte a été refusée par la banque. Vérifiez vos coordonnées ou contactez votre banque avant de réessayer.',
            failedHintExpired:    'Votre carte semble expirée. Veuillez mettre à jour vos informations bancaires et réessayer avec une carte valide.',
            failedHintAuth:       "L'authentification 3-D Secure a échoué. Veuillez réessayer et suivre les étapes de vérification envoyées par votre banque.",
            failedHintTimeout:    'La session de paiement a expiré. Cela peut arriver si la page est restée ouverte trop longtemps. Veuillez réessayer.',
          },

          form: {
            firstName: { label: 'Prénom', required: 'Votre prénom est obligatoire' },
            lastName:  { label: 'Nom',    required: 'Votre nom est obligatoire'    },
            fullName: 'Nom et prénom',
            email:   { label: 'E-mail',  required: 'Votre e-mail est obligatoire'   },
            address: { label: 'Adresse', required: 'Votre adresse est obligatoire'  },
            city:    { label: 'Ville',   required: 'Votre ville est obligatoire'    },
            country: { label: 'Pays', required: 'Votre pays est requis' },
            phone: {
              label:         'N° de téléphone',
              required:      'Votre N° téléphone est obligatoire',
              minLength:     'Minimum 10 caractères',
              invalidLength: 'La longueur du numéro de téléphone est invalide',
              invalidFormat: 'Entrez un numéro valide : 06.., 07.. ou +212..',
            },
            save: 'Sauvegarder',
            saveChanges: 'Sauvegarder les modifications',
            modify: 'Modifier',
            submit: 'Soumettre',
            clientInfo: 'Informations du client',
            selectCity: 'Sélectionnez votre ville',
          },

          review: {
            title: 'Avis sur les produits',
            add: 'Ajouter votre avis',
            submit: "Ajouter l'avis",
            stars: 'Étoiles',
            username: "Nom d'utilisateur",
            yourReview: 'Votre avis',
            firstReview: 'Publier le premier avis !',
            fillAllFields: 'Veuillez remplir tous les champs avant de soumettre.',
            city1: 'Acheteur vérifié',
            city2: 'Acheteur vérifié',
            city3: 'Acheteur vérifié',
          },

          pagination: { next: 'Suivant', previous: 'Précédent' },

          ui: {
            loading: 'Chargement . . .',
            back: 'Retour',
            search: 'Recherche',
            reset: 'Réinitialiser',
            enterName: 'Saisir un nom',
            enterRef: 'Saisir une référence',
            save: 'Sauvegarder',
          },

          home: {
            promotions: 'Nos offres et promotions',
            products: 'Nos produits',
            goToShoes: 'Aller à la section des chaussures',
            goToSandals: 'Aller à la section des sandales',
            goToShirts: 'Aller à la section des chemises',
            goToPants: 'Aller à la section des pantalons',
            moreShoes: 'Plus de chaussures',
            moreSandals: 'Plus de sandales',
            moreShirts: 'Plus de chemises',
            morePants: 'Plus de pantalons',

            hero: {
              cta: 'Acheter maintenant',
              howItWorks: 'Comment ça marche',
              slide1: {
                tag: 'Nouvelle collection',
                headline: 'Trouvez votre style, en quelques clics',
                sub: 'Chaussures, sandales, chemises et pantalons — une sélection livrée chez vous.',
              },
              slide2: {
                tag: 'Tendance du moment',
                headline: 'Le confort à chaque pas, cette saison',
                sub: 'Des sandales pensées pour les beaux jours.',
              },
              slide3: {
                tag: 'Nouveauté',
                headline: 'Des chemises fraîches, pour tous les jours',
                sub: 'Des coupes décontractées et soignées qui vous suivent partout.',
              },
            },

            shopByCategory: 'Acheter par catégorie',
            shopByCategorySub: 'Tout ce dont vous avez besoin, organisé simplement — choisissez une catégorie pour commencer.',

            featured: 'Nouveautés',
            featuredSub: 'Du nouveau stock ajouté régulièrement — découvrez les dernières arrivées.',
            viewAll: 'Voir tous les produits',

            cat: {
              fallbackDesc: 'Découvrez toute la gamme',
              shoeDesc: 'Styles quotidiens et sportifs',
              sandalDesc: 'Confort léger pour les beaux jours',
              shirtDesc: 'Coupes décontractées et soignées',
              pantDesc: 'Coupes modernes pour tous les jours',
            },
          },

          trust: {
            delivery: 'Livraison rapide',
            deliverySub: 'Suivi de commande jusqu’à votre porte',
            quality: 'Qualité vérifiée',
            qualitySub: 'Chaque article est inspecté avant l’envoi',
            secure: 'Paiement sécurisé',
            secureSub: 'Vos informations restent protégées',
            support: 'Support réactif',
            supportSub: 'Nous répondons en quelques heures',
          },

          hiw: {
            title: 'Acheter en toute simplicité',
            sub: 'De la sélection à votre porte — quatre étapes faciles.',
            step1: { title: 'Parcourez la collection', desc: 'Explorez chaussures, sandales, chemises et pantalons. Filtrez par taille, style ou prix.' },
            step2: { title: 'Choisissez votre taille', desc: 'Seules les tailles disponibles sont affichées, aucune surprise au moment de payer.' },
            step3: { title: 'Passez votre commande', desc: 'Ajoutez au panier et confirmez vos informations — aucun compte requis.' },
            step4: { title: 'Recevez votre colis', desc: 'Nous livrons à votre porte. Suivez votre commande à chaque étape.' },
          },

          promo: {
            title: "Cette semaine, une réduction jusqu'à",
            sub: 'Une sélection de styles est en promotion en ce moment. De nouvelles offres chaque semaine.',
            cta: 'Voir les offres',
          },

          testimonials: {
            title: 'Ce que disent nos clients',
            sub: 'De vrais avis de vrais clients.',
            r1: "Très bonne qualité et la taille était parfaite. La livraison a été plus rapide que prévu.",
            r2: 'Confortable, bien fabriqué et facile à commander. Je reviendrai.',
            r3: 'Commande facile et le colis est arrivé en parfait état. Je recommande vivement.',
          },

          newsletter: {
            eyebrow: 'Restez informé',
            title: 'Nouveautés et offres exclusives, en avant-première',
            sub: 'Inscrivez-vous pour être informé dès l’arrivée des nouveaux styles.',
            cta: 'M’informer',
            invalid: 'Veuillez saisir une adresse e-mail valide.',
            success: 'Inscription réussie — surveillez votre boîte mail.',
            thanks: 'Merci ! Nous restons en contact.',
          },

          admin: {
            orders: {
              remaining:         'Commandes en attente',
              waitingDelivery:   'En attente de livraison',
              delivered:         'Commandes livrées',
              all:               'Toutes les commandes',
              notConfirmed:      'Commandes non confirmées',
              showAll:           'Afficher toutes les commandes',
              noRemaining:       'Aucune commande en attente pour le moment',
              noWaitingDelivery: 'Aucune commande en attente de livraison',
              noDelivered:       'Aucune commande livrée pour le moment',
              noOrders:          'Aucune commande pour le moment',
              noProducts:        'Aucun produit trouvé pour cette commande',
              treated:           'La commande a été traitée avec succès',
              alreadyTreated:    'La commande a déjà été traitée',
              process:           'Traiter',
              waiting:           'En attente',
              done:              'Faite',
              treated_label:     'Traitée',
              status:            'État',
              date:              'Date',
              action:            'Action',
              extractDeliveryForm: 'Extraire le formulaire de livraison',
              extractSuccess:    'Le formulaire de livraison a été extrait avec succès',
            },
            deficiency: {
              title:             'Déficit de quantité',
              current:           'Déficiences actuelles',
              showAll:           'Afficher toutes les déficiences',
              process:           'Traiter',
              message:           'Veuillez traiter les déficiences, puis traiter la commande !',
              confirm:           'Confirmer le traitement de la déficience',
              success:           'La déficience a été traitée avec succès',
              error:             'Échec du traitement de la déficience. Veuillez réessayer.',
              noFound:           'Aucune déficience trouvée',
              quantityRequested: 'Quantité demandée',
            },
            product: {
              select:           'Choisissez un produit',
              mainImage:        'Image principale',
              additionalImages: 'Images supplémentaires',
              newer:            'Produit plus récent',
              uploadedImages:   'Images téléchargées',
              delete:           'Supprimer un produit',
              modify:           'Modifier un produit',
              addData:          'Ajouter les données du produit',
              add:              'Ajouter un produit',
              advancedSearch:   'Recherche avancée',
              management:       'Gestion des produits',
              managementOf:     'Gestion des produits de',
              noChosen:         'Pas de produit choisi',
              noData:           'Ce produit ne contient pas de données',
              orderedProducts:  'Produits commandés',
              noCategoryData:   'Pas de données de catégorie',
              categoryError:    "Ajoutez d'abord une catégorie au produit dans les paramètres, puis ajoutez-en une",
              addTypes:         'Ajouter des types de produits',
              addCategories:    'Ajouter des catégories de produits',
              selectType:       'Sélectionnez le type de produit',
              selectCategory:   'Choisissez une catégorie',
            },
            overview: { general: 'Aperçu général', notDeveloped: 'Pas encore développé' },
            users: {
              manager:             "Gestion d'utilisateurs",
              add:                 'Ajouter un utilisateur',
              username:            "Nom d'utilisateur",
              password:            'Mot de passe',
              confirmPassword:     'Confirmer le mot de passe',
              passwordMismatch:    'Les mots de passe ne correspondent pas',
              role:                'Rôle',
              selectRole:          'Choisissez un rôle',
              manager_role:        'Manager',
              admin_role:          'Admin',
              deliveryMan:         'Livreur',
              registrationSuccess: "L'inscription a réussi",
            },
          },

          account: {
            profileTitle:    'Mon profil',
            tabOrders:       'Mes commandes',
            tabProfile:      'Mon profil',
            noOrders:        "Vous n'avez pas encore de commandes.",
            ordersError:     'Impossible de charger vos commandes. Veuillez réessayer.',
            saveSuccess:     'Profil mis à jour avec succès.',
            saveError:       'Impossible de sauvegarder les modifications. Veuillez réessayer.',
            statOrders:      'Commandes',
            statConfirmed:   'Confirmées',
            statDelivered:   'Livrées',
            statSpent:       'Total dépensé',
            statusConfirmed: 'Confirmée',
            statusCod:       'Paiement à la livraison',
            statusPending:   'En attente',
            statusFailed:    'Échouée',
            delivered:       'Livrée',
            onlinePayment:   'Paiement en ligne',
            codPayment:      'Paiement à la livraison',
            articles:        'articles',
            article:         'article',
            loyaltyPerks:    'Avantages fidélité',
            loyaltyLabel:    'Niveau de fidélité',
            loyaltyToNext:   'Points restants pour atteindre le niveau suivant',
            loyaltyPoints:   'Points de fidélité',
            confirmSaveTitle: 'Enregistrer les modifications',
            confirmSaveSub:   'Êtes-vous sûr de vouloir enregistrer vos modifications ?',
            noChanges:        'Aucune modification n\'a été effectuée',
            changeAvatar:     'Changer l`\'avatar',
            // ── Order status pipeline (customer account view) ────────────
            stepPlaced:        'Commande passée',
            stepPayment:       'Paiement',
            stepProcessing:    'Traitement',
            stepDelivery:      'Livraison',
            processingOngoing: 'En cours de préparation',
            processingDone:    'Prête',
            paymentFailed:     'Paiement échoué',
            paymentFailedNote: "Votre paiement n'a pas pu être confirmé, cette commande est donc en attente. Merci de nous contacter ou de passer une nouvelle commande.",
            readyToShip:       'Prête à expédier',
            outForDelivery:    'En cours de livraison',
          },

          tracking: {
            title:         "Suivi de l'état des commandes",
            enterOrderId:  'Entrez votre ID de commande ou le nom',
            placeholder:   'ID commande ou nom client',
            search:        'Rechercher',
            searching:     'Recherche de la commande',
            notValidated:  'Votre commande est en cours de validation',
            validated:     'Votre commande est validée et elle est en route vers vous',
            attempts:      'Tentatives de recherche',
            limitReached:  'Vous avez atteint la limite de tentatives de recherche. Vous pourrez réessayer demain.',
            noValidId:     "n'est pas un ID de commande valide",
            noOrderFound:  "Aucune commande n'est associée à l'ID de commande fourni",
            idProvided:    'ID de commande fourni',
            hint:          'Saisissez le numéro de commande ou le nom du client pour afficher les détails.',
            orderDetails:  'Détails de la commande',
            orderId:       'ID commande',
            date:          'Date',
            paymentMode:   'Mode de paiement',
            paymentStatus: 'Statut du paiement',
            delivery:      'Livraison',
            total:         'Total',
            products:      'Produits commandés',
            product:       'Produit',
            category:      'Catégorie',
            size:          'Taille',
            qty:           'Qté',
            price:         'Prix',
            newSearch:     'Nouvelle recherche',
            goBack:        'Retour',
            limitHint:     'Veuillez patienter puis réessayer plus tard.',
            pending:       'En attente',
            delivered:     'Livré',
            failed:        'Paiement échoué',
            cod:           'Paiement à la livraison',
            processing:    'En cours',
            online:        'Paiement en ligne',
            inProgress:    'En cours',
          },

          auth: {
            welcomeBack:    'Content de te revoir !',
            usernameLabel: 'Nom d\'Utilisaeur',
            signOut:        'Déconnexion',
            signIn:         'Se connecter',
            myAccount:      'Mon compte',
            signInTitle:          'Bon retour',
            signInBtn:            'Se connecter',
            noAccount:            'Pas encore de compte ?',
            createOne:            'En créer un',
            signUpTitle:          'Créer votre compte',
            signUpBtn:            'Créer mon compte',
            haveAccount:          'Déjà un compte ?',
            signInLink:           'Se connecter',
            successTitle:         'Vérifiez votre boîte mail !',
            successSub:           "Nous avons envoyé un lien d'activation à {{email}}. Cliquez dessus pour activer votre compte.",
            goToSignIn:           'Aller à la connexion',
            emailLabel:           'Adresse e-mail',
            emailPlaceholder:     'vous@exemple.com',
            passwordLabel:        'Mot de passe',
            confirmPasswordLabel: 'Confirmer le mot de passe',
            firstNameLabel:       'Prénom',
            firstNamePlaceholder: 'Youssef',
            lastNameLabel:        'Nom',
            lastNamePlaceholder:  'Alaoui',
            phoneLabel:           'Téléphone (optionnel)',
            phonePlaceholder:     '+212 6XX XXX XXX',
            addressLabel:         'Adresse (optionnelle)',
            addressPlaceholder:   '12 Rue Mohammed V, Casablanca',
            passwordHint:         'Minimum 8 caractères.',
            passwordMismatch:     'Les mots de passe ne correspondent pas.',
            passwordTooShort:     'Le mot de passe doit contenir au moins 8 caractères.',
            showPassword:         'Afficher le mot de passe',
            hidePassword:         'Masquer le mot de passe',
            genericError:         'Une erreur est survenue. Veuillez réessayer.',
            brandTagline:         'Mode premium livrée partout au Maroc.',
            checkoutHowToContinue: 'Comment souhaitez-vous continuer ?',
            checkoutSub:           'Connectez-vous pour un paiement plus rapide et le suivi de vos commandes.',
            checkoutWithAccount:   'Continuer avec mon compte',
            checkoutWithAccountSub:'Vos informations pré-remplies et suivi de commandes.',
            checkoutAsGuest:       "Continuer en tant qu'invité",
            checkoutAsGuestSub:    'Aucun compte requis. Remplissez vos informations manuellement.',
            continueAsGuest:       'Passer en invité',
            guestNudge:            'Gagnez du temps à votre prochain achat —',
            or:                    'ou',
            activating:            'Activation de votre compte…',
            activateSuccessTitle:  'Compte activé !',
            activateSuccessSub:    'Votre compte est maintenant actif. Bienvenue sur Al-Firdaous Store !',
            activateAlreadyTitle:  'Déjà activé',
            activateAlreadySub:    'Votre compte est déjà actif. Vous pouvez vous connecter.',
            activateErrorTitle:    'Lien invalide',
            activateErrorSub:      "Ce lien d'activation est invalide ou a déjà été utilisé.",
            activateRedirect:      'Redirection vers la connexion dans {{seconds}}s…',
            // ── Password strength meter ──────────────────────────────────
            strengthLength:   '8 caractères minimum',
            strengthUppercase:'Une lettre majuscule',
            strengthNumber:   'Un chiffre',
            strengthSpecial:  'Un caractère spécial',
            strengthWeak:     'Faible',
            strengthFair:     'Passable',
            strengthGood:     'Bon',
            strengthStrong:   'Fort',
            passwordsMatch:   'Les mots de passe correspondent',
          },

          footer: {
            followUs:            'Suivez-nous',
            contactUs:           'Contactez-nous',
            policies:            'Politiques',
            privacyPolicy:       'Politique de confidentialité',
            usePolicy:           "Conditions générales d'utilisation",
            policiesNotAccepted: "Veuillez accepter les conditions d'utilisation et la politique de confidentialité.",
          },

          error: {
            elementNotFound: "L'élément n'est pas trouvé !",
            pageNotFound:    "Oups ! Cette page n'existe pas.",
          },
        },
      },

      // ════════════════════════════════════════════════════════════════════
      // ARABIC
      // ════════════════════════════════════════════════════════════════════
      ar: {
        translation: {
          nav: {
            home: 'الرئيسية',
            menu: 'القائمة',
            cart: 'السلة',
            orders: 'الطلبيات',
            settings: 'الإعدادات',
            statistics: 'الإحصائيات',
            signOut: 'تسجيل الخروج',
          },

          product: {
            type: 'نوع المنتج',
            settings: 'إعدادات المنتج',
            label: 'المنتج',
            soldOut: 'نفذ',
            sizes: 'المقاسات',
            price: 'السعر',
            currency: 'د.م',
            preview: 'معاينة المنتج',
            info: 'تفاصيل المنتج',
            details: 'تفاصيل المنتج',
            reviews: 'مراجعات المنتج',
            loading: 'جاري تحميل المنتجات...',
            noneYet: 'منتجات جديدة قادمة !',
            stayTuned: 'ترقبوا !',
            view: 'معاينة المنتج',
            addToCart: 'اضافة الى السلة',
            size: 'المقاس',
            category: 'الصنف',
            ref: 'المرجع',
            name: 'الاسم',
            before: 'قبل',
            promotion: 'عرض خاص',
            off: 'تخفيض',
            readMore: 'رؤية الكل',
            readLess: 'رؤية أقل',
            quantity: 'الكمية',
            availability: 'التوفر',
          },

          productTypes: {
            shoe: 'الأحذية',
            sandal: 'صنادل',
            shirt: 'أقمصة',
            pant: 'سراويل',
          },

          cart: {
            title: 'السلة',
            empty: 'لا يوجد أي سلع في سلة التسوق الخاصة بك',
            clear: 'إفراغ السلة',
            toCart: 'الرجوع الى السلة',
            addSuccess: 'تمت إضافة عنصر جديد الى السلة !',
            sizeNotSelected: 'لم يتم اختيار مقاس محدد !',
            quantityAction: 'الكمية/إجراء',
            total: 'المجموع',
            cleared: 'تم تفريغ السلة',
            itemRemoved: 'تم حذف العنصر',
            shopNow: 'تسوق الآن',
          },

          order: {
            summary: 'ملخص الطلبية',
            shipping: 'النقل',
            other: 'أخرى',
            totalAmount: 'المبلغ الإجمالي',
            yourOrder: 'طلبيتكم',
            orderId: 'معرف الطلبية',
            checkoutNow: 'الدفع الآن !',
            details: 'تفاصيل الطلبية',
          },

          confirm: {
            removeItem: 'هل أنت متأكد أنك تريد إزالة هذا العنصر؟',
            removeAll: 'هل أنت متأكد أنك تريد حذف كافة العناصر؟',
            deleteTitle: 'تأكيد الحذف',
            clearAllItems: 'حذف الكل',
            remove: 'حذف',
            cancelBack: 'الإلغاء و العودة',
            delete: 'حذف',
          },

          delivery: {
            label: 'التوصيل',
            free: 'مجاني',
            time: 'موعد التسليم',
            expected: 'المتوقع',
            from: 'من',
            to: 'الى',
            cityOnly: 'حاليا، التوصيل متاح فقط لمدينة العيون',
          },

          payment: {
            portal: 'بوابة الدفع',
            creditCard: 'بطاقة بنكية',
            cod: 'الدفع عند الاستلام COD',
            choose: 'المرجو اختيار طريقة الدفع !',
            chosen: 'طريقة الدفع المختارة',
            notChosen: 'لم يتم اختياره بعد !',
            methods: 'طرق الدفع',
            pay: 'دفع',
            checkoutAlert: 'قم أولاً بملء نموذج الدفع، ثم اختر طريقة الدفع 👍🏻',
            overlayUrlTitle:      'بدء عملية الدفع',
            overlayUrlSub:        'جاري إعداد جلستك الآمنة…',
            overlayCodTitle:      'جاري تسجيل طلبيتكم',
            overlayCodSub:        'جاري تأكيد طلبيتكم…',
            overlayRedirectTitle: 'جاري التوجيه نحو الدفع',
            overlayRedirectSub:   'سيتم توجيهكم إلى صفحة الدفع…',
          },

          transaction: {
            info: 'معلومات التحويل',
            code: 'الرمز',
            currency: 'العملة',
            amount: 'المبلغ',
            transactionId: 'معرف التحويل',
            success: 'اكتملت معاملتك بنجاح',
            downloadTicket: 'تنزيل تذكرة الطلبية',
            thank: 'شكرا على ثقتكم !',
            verifying:            'التحقق من الدفع',
            verifyingSub:         'جاري التأكيد مع بوابة الدفع…',
            processing:           'معالجة الطلبية',
            processingSub:        'جاري تسجيل طلبيتكم…',
            emailing:             'إرسال الفاتورة',
            emailingSub:          'جاري إرسال الإيصال إلى بريدكم…',
            done:                 'تم بنجاح !',
            doneSub:              'جاري إعادة التوجيه…',
            pleaseWait:           'يرجى الانتظار…',
            attemptOf:            'المحاولة {{current}} من {{max}}',
            waitingBeforeRetry:   'انتظار قبل المحاولة {{current}} من {{max}}…',
            retryTitle:           'تعذّر تأكيد الدفع',
            retryDefaultReason:   'تعذّر التحقق من دفعتكم. يرجى المحاولة مجدداً.',
            retryLabel:           'التحويل',
            retryOrder:           'الطلبية',
            retryBtn:             'إعادة المحاولة',
            cancelBtn:            'إلغاء الطلبية',
            retryNote:            'لا تزال عناصرك محجوزة. ستعيدك المحاولة إلى صفحة الدفع دون إنشاء طلبية جديدة.',
            retryBusy:            'يرجى الانتظار…',
            errorTitle:           'حدث خطأ ما',
            errorNote:            'يرجى التواصل مع فريق الدعم مع التفاصيل أعلاه.',
            failedTitle:          'فشل الدفع',
            failedDefaultMsg:     'حدث خطأ أثناء معالجة دفعتكم.',
            failedOrderId:        'معرف الطلبية',
            failedTransactionId:  'معرف التحويل',
            failedErrorCode:      'رمز الخطأ',
            failedSupportNote:    'يرجى الاحتفاظ بمعرف التحويل والتواصل مع الدعم إذا تم خصم المبلغ.',
            failedGoHome:         'الرئيسية',
            failedTryAgain:       'إعادة المحاولة',
            failedCategory_cancelled:          'تم إلغاء الدفع',
            failedCategory_insufficient_funds: 'رصيد غير كافٍ',
            failedCategory_card_declined:      'تم رفض البطاقة',
            failedCategory_card_expired:       'البطاقة منتهية الصلاحية',
            failedCategory_auth_failed:        'فشل التحقق 3-D Secure',
            failedCategory_timeout:            'انتهت مهلة الجلسة',
            failedCategory_generic:            'فشل الدفع',
            failedHintCancelled:  'لقد ألغيت عملية الدفع. لا تزال عناصرك محجوزة — انقر على "إعادة المحاولة" للعودة إلى صفحة الدفع.',
            failedHintFunds:      'تم رفض بطاقتك بسبب عدم كفاية الرصيد. يرجى استخدام بطاقة أخرى أو شحن حسابك والمحاولة مجدداً.',
            failedHintDeclined:   'تم رفض بطاقتك من قِبل البنك. يرجى مراجعة بيانات البطاقة أو التواصل مع البنك قبل إعادة المحاولة.',
            failedHintExpired:    'يبدو أن بطاقتك منتهية الصلاحية. يرجى تحديث بياناتك البنكية والمحاولة مرة أخرى ببطاقة سارية.',
            failedHintAuth:       'فشل التحقق 3-D Secure. يرجى إعادة المحاولة واتباع خطوات التحقق التي أرسلها البنك.',
            failedHintTimeout:    'انتهت مهلة جلسة الدفع. قد يحدث هذا إذا تركت الصفحة مفتوحة طويلاً. يرجى المحاولة مجدداً.',
          },

          form: {
            firstName: { label: 'الاسم',             required: 'الاسم مطلوب'                    },
            lastName:  { label: 'اللقب',             required: 'اللقب مطلوب'                    },
            fullName: 'الاسم الكامل',
            email:   { label: 'البريد الإلكتروني',  required: 'البريد الإلكتروني مطلوب'         },
            address: { label: 'العنوان',             required: 'العنوان مطلوب'                   },
            city:    { label: 'المدينة',             required: 'المدينة مطلوبة'                  },
            country: { label: 'البلد', required: 'بلدك مطلوب' },
            phone: {
              label:         'رقم الهاتف',
              required:      'رقم الهاتف مطلوب',
              minLength:     '10 أحرف على الأقل',
              invalidLength: 'طول رقم الهاتف غير صحيح',
              invalidFormat: 'أدخل رقمًا صحيحًا: 06.. أو 07.. أو +212..',
            },
            save: 'حفظ',
            saveChanges: 'حفظ التعديلات',
            modify: 'تعديل',
            submit: 'إرسال',
            clientInfo: 'معلومات العميل',
            selectCity: 'اختر مدينتك',
          },

          review: {
            title: 'مراجعات المنتج',
            add: 'إضافة تقييمك',
            submit: 'إضافة التقييم',
            stars: 'نجوم',
            username: 'اسم المستخدم',
            yourReview: 'تقييمك',
            firstReview: 'كن أول من يضع تقييمًا !',
            fillAllFields: 'يرجى ملء جميع الحقول قبل الإرسال.',
            city1: 'مشترٍ موثّق',
            city2: 'مشترٍ موثّق',
            city3: 'مشترٍ موثّق',
          },

          pagination: { next: 'التالي', previous: 'السابق' },

          ui: {
            loading: 'جاري التحميل . . .',
            back: 'رجوع',
            search: 'بحث',
            reset: 'إعادة تعيين',
            enterName: 'أدخل اسمًا',
            enterRef: 'أدخل مرجعًا',
            save: 'حفظ',
          },

          home: {
            promotions: 'عروضنا وتخفيضاتنا',
            products: 'منتجاتنا',
            goToShoes: 'الذهاب إلى قسم الأحذية',
            goToSandals: 'الذهاب إلى قسم الصنادل',
            goToShirts: 'الذهاب إلى قسم القمصان',
            goToPants: 'الذهاب إلى قسم السراويل',
            moreShoes: 'المزيد من الأحذية',
            moreSandals: 'المزيد من الصنادل',
            moreShirts: 'المزيد من القمصان',
            morePants: 'المزيد من السراويل',

            hero: {
              cta: 'تسوق الآن',
              howItWorks: 'كيف يعمل المتجر',
              slide1: {
                tag: 'مجموعة جديدة',
                headline: 'اعثر على أسلوبك في خطوات بسيطة',
                sub: 'أحذية، صنادل، قمصان وسراويل — تشكيلة مختارة تصل إلى باب منزلك.',
              },
              slide2: {
                tag: 'الأكثر رواجاً',
                headline: 'الراحة في كل خطوة هذا الموسم',
                sub: 'صنادل يومية مصممة للأيام الدافئة.',
              },
              slide3: {
                tag: 'وصل حديثاً',
                headline: 'قمصان جديدة لكل يوم',
                sub: 'قصّات عصرية وأنيقة تواكب أسلوبك.',
              },
            },

            shopByCategory: 'تسوق حسب الفئة',
            shopByCategorySub: 'كل ما تحتاجه، منظم ببساطة — اختر فئة لبدء التصفح.',

            featured: 'وصل حديثاً',
            featuredSub: 'منتجات جديدة تضاف بانتظام — اكتشف آخر الإضافات.',
            viewAll: 'عرض كل المنتجات',

            cat: {
              fallbackDesc: 'اكتشف التشكيلة الكاملة',
              shoeDesc: 'تصاميم يومية ورياضية',
              sandalDesc: 'راحة خفيفة لأيام الصيف',
              shirtDesc: 'قصّات عصرية وأنيقة',
              pantDesc: 'قصّات عصرية لكل يوم',
            },
          },

          trust: {
            delivery: 'توصيل سريع',
            deliverySub: 'تتبع الشحنة حتى باب منزلك',
            quality: 'جودة مفحوصة',
            qualitySub: 'كل منتج يخضع للفحص قبل الشحن',
            secure: 'دفع آمن',
            secureSub: 'بياناتك تبقى محمية دائماً',
            support: 'دعم متجاوب',
            supportSub: 'نرد عليك خلال ساعات قليلة',
          },

          hiw: {
            title: 'التسوق بكل بساطة',
            sub: 'من التصفح إلى باب منزلك — أربع خطوات سهلة.',
            step1: { title: 'تصفح المجموعة', desc: 'اكتشف الأحذية والصنادل والقمصان والسراويل. صفِّ حسب المقاس أو النمط أو السعر.' },
            step2: { title: 'اختر مقاسك', desc: 'تُعرض فقط المقاسات المتوفرة، فلا مفاجآت عند الدفع.' },
            step3: { title: 'أتمم طلبيتك', desc: 'أضف إلى السلة وأكّد بياناتك — لا حاجة لإنشاء حساب.' },
            step4: { title: 'استلم طلبيتك', desc: 'نوصلها إلى باب منزلك. تتبّع طلبيتك في كل خطوة.' },
          },

          promo: {
            title: "خصم يصل هذا الأسبوع الى",
            sub: 'تشكيلة مختارة معروضة بالتخفيض الآن. عروض جديدة كل أسبوع.',
            cta: 'مشاهدة العروض',
          },

          testimonials: {
            title: 'ماذا يقول عملاؤنا',
            sub: 'تقييمات حقيقية من عملاء حقيقيين.',
            r1: 'جودة رائعة والمقاس كان مضبوطاً تماماً. التوصيل كان أسرع مما توقعت.',
            r2: 'مريح وذو صناعة جيدة وسهل الطلب. سأعود للشراء مجدداً.',
            r3: 'عملية الدفع كانت سهلة والطرد وصل بحالة ممتازة. أنصح به بشدة.',
          },

          newsletter: {
            eyebrow: 'ابق على اطلاع',
            title: 'إصدارات جديدة وعروض حصرية، أولاً',
            sub: 'انضم إلى قائمتنا لتكون أول من يعلم بوصول التشكيلات الجديدة.',
            cta: 'أعلمني',
            invalid: 'يرجى إدخال بريد إلكتروني صالح.',
            success: 'تم التسجيل — تابع بريدك الإلكتروني.',
            thanks: 'شكراً لك! سنتواصل معك قريباً.',
          },

          admin: {
            orders: {
              remaining:         'الطلبيات المتبقية',
              waitingDelivery:   'في انتظار التسليم',
              delivered:         'الطلبيات المسلمة',
              all:               'كل الطلبيات',
              notConfirmed:      'الطلبيات غير المؤكدة',
              showAll:           'عرض كل الطلبيات',
              noRemaining:       'لا توجد طلبية متبقية',
              noWaitingDelivery: 'لا توجد طلبية في انتظار التسليم',
              noDelivered:       'لم يتم تسليم أي طلبية بعد',
              noOrders:          'لا توجد طلبيات بعد',
              noProducts:        'لم يتم العثور على منتجات لهذه الطلبية',
              treated:           'تمت معالجة الطلبية بنجاح',
              alreadyTreated:    'الطلبية تمت معالجتها بالفعل',
              process:           'معالجة',
              waiting:           'انتظار',
              done:              'تمت',
              treated_label:     'تمت المعالجة',
              status:            'الحالة',
              date:              'التاريخ',
              action:            'الإجراء',
              extractDeliveryForm: 'استخراج نموذج التسليم',
              extractSuccess:    'تم استخراج نموذج التسليم بنجاح',
            },
            deficiency: {
              title:             'نقص الكميات',
              current:           'النقص الحالي',
              showAll:           'عرض كل النقصات',
              process:           'معالجة',
              message:           'يرجى معالجة النقصات أولاً، ثم معالجة الطلبية !',
              confirm:           'تأكيد معالجة النقص',
              success:           'تمت معالجة النقص بنجاح',
              error:             'فشل معالجة النقص. يرجى المحاولة مجدداً.',
              noFound:           'لم يتم العثور على أي نقص',
              quantityRequested: 'الكمية المطلوبة',
            },
            product: {
              select:           'اختر منتجًا',
              mainImage:        'الصورة الرئيسية',
              additionalImages: 'صور إضافية',
              newer:            'منتج حديث',
              uploadedImages:   'الصور المحملة',
              delete:           'حذف منتج',
              modify:           'تعديل المنتج',
              addData:          'إضافة بيانات المنتج',
              add:              'إضافة منتج',
              advancedSearch:   'بحث متقدم',
              management:       'إدارة المنتجات',
              managementOf:     'إدارة المنتجات الخاصة ب',
              noChosen:         'لم يتم اختيار أي منتج',
              noData:           'هذا المنتج لا يحتوي على أي بيانات',
              orderedProducts:  'المنتجات المطلوبة',
              noCategoryData:   'لا توجد بيانات الفئة',
              categoryError:    'أضف فئة للمنتج في الإعدادات أولاً، ثم أضف منتجا',
              addTypes:         'إضافة أنواع المنتجات',
              addCategories:    'إضافة فئات المنتجات',
              selectType:       'حدد نوع المنتج',
              selectCategory:   'المرجو اختيار صنف',
            },
            overview: { general: 'نظرة عامة', notDeveloped: 'لم يتم تطويره بعد' },
            users: {
              manager:             'إدارة المستخدمين',
              add:                 'إضافة مستخدم',
              username:            'اسم المستخدم',
              password:            'كلمة المرور',
              confirmPassword:     'تأكيد كلمة المرور',
              passwordMismatch:    'كلمات المرور غير متطابقة',
              role:                'الدور',
              selectRole:          'المرجو اختيار دور',
              manager_role:        'مشرف',
              admin_role:          'مدير',
              deliveryMan:         'رجل التوصيل',
              registrationSuccess: 'تم التسجيل بنجاح',
            },
          },

          account: {
            profileTitle:    'ملفي الشخصي',
            tabOrders:       'طلبياتي',
            tabProfile:      'ملفي الشخصي',
            noOrders:        'ليس لديك أي طلبيات بعد.',
            ordersError:     'تعذّر تحميل طلبياتك. يرجى المحاولة مجدداً.',
            saveSuccess:     'تم تحديث الملف الشخصي بنجاح.',
            saveError:       'تعذّر حفظ التعديلات. يرجى المحاولة مجدداً.',
            statOrders:      'الطلبيات',
            statConfirmed:   'مؤكدة',
            statDelivered:   'مسلّمة',
            statSpent:       'المجموع المنفق',
            statusConfirmed: 'مؤكدة',
            statusCod:       'الدفع عند الاستلام',
            statusPending:   'قيد الانتظار',
            statusFailed:    'فاشلة',
            delivered:       'مسلّمة',
            onlinePayment:   'دفع إلكتروني',
            codPayment:      'الدفع عند الاستلام',
            articles:        'منتجات',
            article:         'منتج',
            loyaltyPerks:    'مزايا برنامج الوفاء',
            loyaltyLabel:    'مستوى العضوية',
            loyaltyToNext:   'النقاط المتبقية للوصول إلى المستوى التالي',
            loyaltyPoints:   'نقاط الوفاء',
            confirmSaveTitle: 'حفظ التغييرات',
            confirmSaveSub:   'هل أنت متأكد من رغبتك في حفظ التغييرات؟',
            noChanges:        'لم يتم إجراء أي تغييرات',
            changeAvatar:     'تغيير الصورة الشخصية',
            // ── Order status pipeline (customer account view) ────────────
            stepPlaced:        'تم تأكيد الطلبية',
            stepPayment:       'الدفع',
            stepProcessing:    'المعالجة',
            stepDelivery:      'التوصيل',
            processingOngoing: 'قيد التحضير',
            processingDone:    'جاهزة',
            paymentFailed:     'فشل الدفع',
            paymentFailedNote: 'تعذّر تأكيد دفعتكم، لذا هذه الطلبية معلّقة حالياً. يرجى التواصل معنا أو إتمام طلبية جديدة.',
            readyToShip:       'جاهزة للشحن',
            outForDelivery:    'في طريقها للتسليم',
          },

          tracking: {
            title:         'تتبع حالة الطلبية',
            enterOrderId:  'أدخل رقم الطلبية أو الاسم',
            placeholder:   'رقم الطلبية أو اسم الزبون',
            search:        'بحث',
            searching:     'البحث عن الطلبية',
            notValidated:  'جاري معالجة طلبيتكم',
            validated:     'تم معالجة طلبك وهو في طريقه إليك.',
            attempts:      'محاولات البحث',
            limitReached:  'لقد وصلت إلى الحد الأقصى لمحاولات البحث. يمكنك المحاولة مرة أخرى غدًا.',
            noValidId:     'ليس معرف طلبية صالح',
            noOrderFound:  'لا توجد طلبية مرتبطة بمعرف الطلبية المقدم',
            idProvided:    'تم توفير معرف الطلبية التالي',
            hint:          'أدخل رقم الطلبية أو اسم الزبون لعرض تفاصيل الطلبية.',
            orderDetails:  'تفاصيل الطلبية',
            orderId:       'معرف الطلبية',
            date:          'التاريخ',
            paymentMode:   'طريقة الدفع',
            paymentStatus: 'حالة الدفع',
            delivery:      'التوصيل',
            total:         'المجموع',
            products:      'المنتجات المطلوبة',
            product:       'المنتج',
            category:      'الصنف',
            size:          'المقاس',
            qty:           'الكمية',
            price:         'السعر',
            newSearch:     'بحث جديد',
            goBack:        'رجوع',
            limitHint:     'يرجى الانتظار ثم المحاولة لاحقًا.',
            pending:       'قيد الانتظار',
            delivered:     'تم التسليم',
            failed:        'فشل الدفع',
            cod:           'الدفع عند الاستلام',
            processing:    'قيد المعالجة',
            online:        'دفع إلكتروني',
            inProgress:    'قيد التنفيذ',
          },

          auth: {
            welcomeBack:    'مرحبًا بعودتك !',
            usernameLabel: 'اسم المستخدم',
            signOut:        'تسجيل الخروج',
            signIn:         'تسجيل الدخول',
            myAccount:      'حسابي',
            signInTitle:          'مرحباً بعودتك',
            signInBtn:            'تسجيل الدخول',
            noAccount:            'ليس لديك حساب ؟',
            createOne:            'إنشاء حساب',
            signUpTitle:          'إنشاء حسابك',
            signUpBtn:            'إنشاء الحساب',
            haveAccount:          'لديك حساب بالفعل ؟',
            signInLink:           'تسجيل الدخول',
            successTitle:         'تحقق من بريدك !',
            successSub:           'أرسلنا رابط التفعيل إلى {{email}}. انقر عليه لتفعيل حسابك.',
            goToSignIn:           'الذهاب إلى تسجيل الدخول',
            emailLabel:           'البريد الإلكتروني',
            emailPlaceholder:     'you@example.com',
            passwordLabel:        'كلمة المرور',
            confirmPasswordLabel: 'تأكيد كلمة المرور',
            firstNameLabel:       'الاسم',
            firstNamePlaceholder: 'يوسف',
            lastNameLabel:        'اللقب',
            lastNamePlaceholder:  'العلوي',
            phoneLabel:           'الهاتف (اختياري)',
            phonePlaceholder:     '+212 6XX XXX XXX',
            addressLabel:         'العنوان (اختياري)',
            addressPlaceholder:   'شارع محمد الخامس، الدار البيضاء',
            passwordHint:         '8 أحرف على الأقل.',
            passwordMismatch:     'كلمات المرور غير متطابقة.',
            passwordTooShort:     'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.',
            showPassword:         'إظهار كلمة المرور',
            hidePassword:         'إخفاء كلمة المرور',
            genericError:         'حدث خطأ ما. يرجى المحاولة مجدداً.',
            brandTagline:         'موضة راقية تُوصَّل إلى جميع أنحاء المغرب.',
            checkoutHowToContinue: 'كيف تريد المتابعة؟',
            checkoutSub:           'سجّل دخولك للدفع السريع وتتبع طلباتك.',
            checkoutWithAccount:   'المتابعة بحسابي',
            checkoutWithAccountSub:'بيانات مملوءة تلقائياً وتتبع الطلبيات.',
            checkoutAsGuest:       'المتابعة كزبون غير مسجّل',
            checkoutAsGuestSub:    'لا حاجة لحساب. أدخل بياناتك يدوياً.',
            continueAsGuest:       'المتابعة كضيف',
            guestNudge:            'وفّر وقتك في المرة القادمة —',
            or:                    'أو',
            activating:            'جاري تفعيل حسابك…',
            activateSuccessTitle:  'تم تفعيل الحساب !',
            activateSuccessSub:    'حسابك الآن نشط. مرحباً بك في متجر الفردوس !',
            activateAlreadyTitle:  'الحساب مفعّل مسبقاً',
            activateAlreadySub:    'حسابك مفعّل بالفعل. يمكنك تسجيل الدخول.',
            activateErrorTitle:    'رابط غير صالح',
            activateErrorSub:      'رابط التفعيل غير صالح أو تم استخدامه من قبل.',
            activateRedirect:      'إعادة التوجيه إلى تسجيل الدخول خلال {{seconds}} ثوان…',
            // ── Password strength meter ──────────────────────────────────
            strengthLength:   '8 أحرف على الأقل',
            strengthUppercase:'حرف كبير واحد على الأقل',
            strengthNumber:   'رقم واحد على الأقل',
            strengthSpecial:  'رمز خاص واحد على الأقل',
            strengthWeak:     'ضعيفة',
            strengthFair:     'مقبولة',
            strengthGood:     'جيدة',
            strengthStrong:   'قوية',
            passwordsMatch:   'كلمتا المرور متطابقتان',
          },

          footer: {
            followUs:            'تابعنا',
            contactUs:           'تواصل معنا',
            policies:            'السياسات',
            privacyPolicy:       'سياسة الخصوصية',
            usePolicy:           'الشروط العامة للاستخدام',
            policiesNotAccepted: 'يرجى قبول الشروط وسياسة الخصوصية.',
          },

          error: {
            elementNotFound: 'لم يتم العثور على العنصر !',
            pageNotFound:    'أوه ! هذه الصفحة غير موجودة.',
          },
        },
      },
    },

    lng: 'fr',
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
  });

// ── Context ───────────────────────────────────────────────────────────────────

interface LangContextProps {
  currentLang: string;
  setCurrentLang: Dispatch<React.SetStateAction<string>>;
}

const langContext = createContext<LangContextProps | undefined>(undefined);

export const LangContextProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLang] = useState<string>(() => {
    const lang = sessionStorage.getItem('AlFirdaousStoreLang');
    if (lang) return JSON.parse(lang);
    return 'العربية';
  });

  useEffect(() => {
    sessionStorage.setItem('AlFirdaousStoreLang', JSON.stringify(currentLang));
    i18n.changeLanguage(selectedLang(currentLang));
  }, [currentLang]);

  return (
    <langContext.Provider value={{ currentLang, setCurrentLang }}>
      <div>{children}</div>
    </langContext.Provider>
  );
};

export default i18n;

export const useLangContext = (): LangContextProps => {
  const context = useContext(langContext);
  if (context === undefined) {
    throw new Error('useLangContext must be used within a LangContextProvider');
  }
  return context;
};